name: server Test
run-name: ${{ github.actor }} is testing Mern Server
on:
  push:
    branches:
      - server
  workflow_dispatch:
        
jobs:
  serverTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install 
      - run: npm run test
